### ISSUE TITLE
FPS of the entire pipeline on Nano

### ISSUE THREAD

**Issue by poornimajd** [expectopatronm/platooning-demonstrator#1]
Hello,great work!
I wanted to know what was the fps obtained for the entire pipeline,consisting mainly object detection and depth estimation.Were the models loaded sequentially or in parallel?
Thank you

**Comment by expectopatronm** [comment]
Hey!. So the models were loaded sequentially only. FPS was around 7.

**Comment by poornimajd** [comment]
If the models fit in the memory of the gpu ,then loading in parallel should have given a higher fps right?

Thank you

**Comment by expectopatronm** [comment]
Theoretically yes. I remember a CUDA device unavailable error popping up since the models are of different environments, i.e., tensorflow and pytorch. I did try to convert them to a uniform tensorflow implementation but didn’t get very far. Please feel free to try a parallel implementation of the three models.

**Comment by poornimajd** [comment]
Thanks for the reply!
